name: Prettier

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Prettier
        run: npm install --global prettier
      - name: Check formatting with Prettier
        run: prettier --check .
      - name: Format code with Prettier
        run: prettier --write .
